volumes:
  mysql_local:
    driver: local
services:
  db:
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=finaktiva
      - MYSQL_DATABASE=Registration
    image: mysql
    volumes:
      - mysql_local:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
  backend:
    restart: always
    container_name: backend
    depends_on:
      db:
        condition: service_started
    environment:
      - APP_PORT=3000
      - API_PREFIX=/api/v1
      - CORS_ORIGIN=*
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=finaktiva
      - MYSQL_DATABASE=Registration
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    command: sh -c "npm run migrate && node dist/index.js"
  frontend:
    container_name: frontend
    environment:
      - BASE_URL=backend
      - API_VERSION=v1
    ports:
      - 80:80
    build:
      context: frontend
      dockerfile: ./Dockerfile
